--DROP TABLE IF EXISTS BOARD;
--
--CREATE TABLE BOARD
--(
--ID int(10),
--USERID int(10),
--TITLE varchar(200),
--BODY varchar(200)
--);

--INSERT INTO BOARD (ID, USERID, TITLE, BODY) VALUES (1, 1, '게시글 제목1', '게시글 내용1');
--INSERT INTO BOARD (ID, USERID, TITLE, BODY) VALUES (2, 2, '게시글 제목2', '게시글 내용2');
--INSERT INTO BOARD (ID, USERID, TITLE, BODY) VALUES (3, 3, '게시글 제목3', '게시글 내용3');

INSERT INTO BOARD (ID, USER_ID, TITLE, BODY) VALUES (1, 1, 'title 1', 'BODY 1');
INSERT INTO BOARD (ID, USER_ID, TITLE, BODY) VALUES (2, 2, 'title 2', 'BODY 2');
INSERT INTO BOARD (ID, USER_ID, TITLE, BODY) VALUES (3, 3, 'title 3', 'BODY 3');